version: '3.9'

services:
  vtx:
    image: ghcr.io/0-5788719150923125/qdns:1
    restart: 'always'
    user: 1000:1000
    ulimits:
      memlock: -1
      stack: 67108864
    build:
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'